# Catálogo de códigos do core de avaliação

IDADE_OBRIGATORIA_AUSENTE = "IDADE_OBRIGATORIA_AUSENTE"
IDADE_TIPO_INVALIDO = "IDADE_TIPO_INVALIDO"
IDADE_FORA_FAIXA = "IDADE_FORA_FAIXA"
IDADE_MENOR_18 = "IDADE_MENOR_18"

IDADE_ACIMA_60 = "IDADE_ACIMA_60"

